architecture: standalone

auth:
  password: "Workshop123redis"

master:
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"
  persistence:
    size: 512Mi

replica:
  replicaCount: 0

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
