auth:
  adminUser: admin
  adminPassword: "Workshop1!kc"

production: false
proxyHeaders: xforwarded

ingress:
  enabled: true
  hostname: keycloak.k3d.localhost
  ingressClassName: traefik
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  servicePort: http

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack

resources:
  requests:
    cpu: "200m"
    memory: "512Mi"
  limits:
    cpu: "1000m"
    memory: "1Gi"

postgresql:
  enabled: true
  auth:
    postgresPassword: "Workshop123kcpg"
    username: keycloak
    password: "Workshop123kcdb"
    database: keycloak
  primary:
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "250m"
        memory: "256Mi"
